default_settings: null
behaviors:
  TickTack_DCCS:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.003
      beta: 0.00005
      epsilon: 0.25
      lambd: 0.97
      num_epoch: 10
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper
      deterministic: false
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1 #9.98
      # curiosity: 
        # strength: 0.02
        # gamma: 0.99
        # encoding_size: 256
        # learning_rate: 3.0e-4
    init_path: null
    keep_checkpoints: 15
    checkpoint_interval: 1000000
    max_steps: 60000000
    time_horizon: 64
    summary_freq: 50000
    threaded: true
    self_play: null
    behavioral_cloning: null
env_settings:
  env_path: C:\Users\Alex\Downloads\ml-agents-release_19\myEnvs\foos_3Dcore.exe
  env_args: null
  base_port: 5005
  num_envs: 10 #6
  num_areas: 8
  seed: -1
  max_lifetime_restarts: 10
  restarts_rate_limit_n: 1
  restarts_rate_limit_period_s: 60
engine_settings:
  width: 84
  height: 84
  quality_level: 2
  time_scale: 1
  target_frame_rate: -1
  capture_frame_rate: 60
  no_graphics: true
environment_parameters: null
checkpoint_settings:
  run_id: TickTack_DCCS_1.3
  initialize_from: TickTack_DCCS_1.2
  load_model: false
  resume: false
  force: false
  train_model: false
  inference: false
  results_dir: results
torch_settings:
  device: cuda
debug: false
