behaviors:
  Table:
    trainer_type: ppo
    # Trainer configurations common to all trainers
    summary_freq: 10000
    time_horizon: 128
    max_steps: 1.0e6
    keep_checkpoints: 5
    checkpoint_interval: 50000
    init_path: null
    threaded: true

    hyperparameters:
      # Hyperparameters common to PPO and SAC
      learning_rate: 3.0e-4
      batch_size: 2048
      buffer_size: 20480
      learning_rate_schedule: linear

      # PPO-specific hyperparameters
      # Replaces the "PPO-specific hyperparameters" section above
      beta: 2.0e-4
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3
      #shared_critic: False

    # Configuration of the neural network (common to PPO/SAC)
    network_settings:
      vis_encode_type: simple
      normalize: false
      hidden_units: 512
      num_layers: 2